name: My First Workflow

on:
  push:
    branches:
      - main   # mainブランチにPushされたときに実行

jobs:
  greet-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hey!! GitHub Actions! This is a test run."

